{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "zyzx8f85EaPd"
      },
      "source": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 669
        },
        "id": "qqaC3rhX8AaK",
        "outputId": "392720e0-8abc-4eb8-a657-40d33caa7b50"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Welcome to the Comprehensive Scientific Calculator!\n",
            "You can enter any real numbers (positive, negative, decimals) for calculations.\n",
            "\n",
            "Comprehensive Scientific Calculator\n",
            "Select an operation:\n",
            "1. Basic Arithmetic Operations\n",
            "2. Trigonometric Functions\n",
            "3. Logarithmic Functions\n",
            "4. Matrix Operations\n",
            "5. Advanced Operations\n",
            "6. Exit\n",
            "Enter your choice (1-6): 3\n",
            "\n",
            "Logarithmic Functions\n",
            "1. Natural Log (ln)\n",
            "2. Logarithm base 10 (log10)\n",
            "3. Custom Base Logarithm\n",
            "Select a function (1-3): 3\n",
            "Enter number: 445\n",
            "Enter logarithm base: 10\n"
          ]
        },
        {
          "ename": "NameError",
          "evalue": "name 'math' is not defined",
          "output_type": "error",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
            "\u001b[0;32m<ipython-input-1-153c781b478c>\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[1;32m    338\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    339\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0m__name__\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m\"__main__\"\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 340\u001b[0;31m     \u001b[0mmain\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
            "\u001b[0;32m<ipython-input-1-153c781b478c>\u001b[0m in \u001b[0;36mmain\u001b[0;34m()\u001b[0m\n\u001b[1;32m    326\u001b[0m             \u001b[0mtrigonometric_functions\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    327\u001b[0m         \u001b[0;32melif\u001b[0m \u001b[0mchoice\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m'3'\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 328\u001b[0;31m             \u001b[0mlogarithmic_functions\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    329\u001b[0m         \u001b[0;32melif\u001b[0m \u001b[0mchoice\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m'4'\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    330\u001b[0m             \u001b[0mmatrix_operations\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;32m<ipython-input-1-153c781b478c>\u001b[0m in \u001b[0;36mlogarithmic_functions\u001b[0;34m()\u001b[0m\n\u001b[1;32m    131\u001b[0m             \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Error: Logarithm base must be positive and not equal to 1.\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    132\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 133\u001b[0;31m             \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf\"Result: log{base}({num}) = {math.log(num, base)}\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    134\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    135\u001b[0m         \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Invalid choice.\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mNameError\u001b[0m: name 'math' is not defined"
          ]
        }
      ],
      "source": [
        "\n",
        "\n",
        "# Function to display the menu\n",
        "def display_menu():\n",
        "    print(\"\\nComprehensive Scientific Calculator\")\n",
        "    print(\"Select an operation:\")\n",
        "    print(\"1. Basic Arithmetic Operations\")\n",
        "    print(\"2. Trigonometric Functions\")\n",
        "    print(\"3. Logarithmic Functions\")\n",
        "    print(\"4. Matrix Operations\")\n",
        "    print(\"5. Advanced Operations\")\n",
        "    print(\"6. Exit\")\n",
        "\n",
        "# Function to get a valid number from the user (no limits)\n",
        "def get_number(prompt):\n",
        "    while True:\n",
        "        try:\n",
        "            return float(input(prompt))\n",
        "        except ValueError:\n",
        "            print(\"Error: Please enter a valid number (can be any real number).\")\n",
        "\n",
        "# Function to get a valid matrix from the user\n",
        "def get_matrix(prompt):\n",
        "    while True:\n",
        "        try:\n",
        "            print(\"Enter matrix in format '1,2,3;4,5,6' for a 2x3 matrix\")\n",
        "            matrix_input = input(prompt)\n",
        "            matrix = [list(map(float, row.split(','))) for row in matrix_input.split(';')]\n",
        "            return np.array(matrix)\n",
        "        except ValueError:\n",
        "            print(\"Error: Please enter a valid matrix in the format '1,2,3;4,5,6'.\")\n",
        "\n",
        "# Basic arithmetic operations\n",
        "def basic_arithmetic():\n",
        "    print(\"\\nBasic Arithmetic Operations\")\n",
        "    print(\"1. Addition (+)\")\n",
        "    print(\"2. Subtraction (-)\")\n",
        "    print(\"3. Multiplication (*)\")\n",
        "    print(\"4. Division (/)\")\n",
        "    print(\"5. Modulus (%)\")\n",
        "    print(\"6. Floor Division (//)\")\n",
        "\n",
        "    choice = input(\"Select an operation (1-6): \")\n",
        "    num1 = get_number(\"Enter first number: \")\n",
        "    num2 = get_number(\"Enter second number: \")\n",
        "\n",
        "    if choice == '1':\n",
        "        print(f\"Result: {num1} + {num2} = {num1 + num2}\")\n",
        "    elif choice == '2':\n",
        "        print(f\"Result: {num1} - {num2} = {num1 - num2}\")\n",
        "    elif choice == '3':\n",
        "        print(f\"Result: {num1} * {num2} = {num1 * num2}\")\n",
        "    elif choice == '4':\n",
        "        if num2 == 0:\n",
        "            print(\"Error: Division by zero is not allowed.\")\n",
        "        else:\n",
        "            print(f\"Result: {num1} / {num2} = {num1 / num2}\")\n",
        "    elif choice == '5':\n",
        "        print(f\"Result: {num1} % {num2} = {num1 % num2}\")\n",
        "    elif choice == '6':\n",
        "        print(f\"Result: {num1} // {num2} = {num1 // num2}\")\n",
        "    else:\n",
        "        print(\"Invalid choice.\")\n",
        "\n",
        "# Trigonometric functions\n",
        "def trigonometric_functions():\n",
        "    print(\"\\nTrigonometric Functions\")\n",
        "    print(\"1. Sine (sin)\")\n",
        "    print(\"2. Cosine (cos)\")\n",
        "    print(\"3. Tangent (tan)\")\n",
        "    print(\"4. Inverse Sine (sin-1)\")\n",
        "    print(\"5. Inverse Cosine (cos-1)\")\n",
        "    print(\"6. Inverse Tangent (tan-1)\")\n",
        "    print(\"7. Hyperbolic Sine (sinh)\")\n",
        "    print(\"8. Hyperbolic Cosine (cosh)\")\n",
        "    print(\"9. Hyperbolic Tangent (tanh)\")\n",
        "\n",
        "    choice = input(\"Select a function (1-9): \")\n",
        "\n",
        "    if choice in ['1', '2', '3', '7', '8', '9']:\n",
        "        angle = get_number(\"Enter angle in degrees: \")\n",
        "        rad = math.radians(angle)\n",
        "        if choice == '1':\n",
        "            print(f\"Result: sin({angle}°) = {math.sin(rad)}\")\n",
        "        elif choice == '2':\n",
        "            print(f\"Result: cos({angle}°) = {math.cos(rad)}\")\n",
        "        elif choice == '3':\n",
        "            print(f\"Result: tan({angle}°) = {math.tan(rad)}\")\n",
        "        elif choice == '7':\n",
        "            print(f\"Result: sinh({angle}°) = {math.sinh(rad)}\")\n",
        "        elif choice == '8':\n",
        "            print(f\"Result: cosh({angle}°) = {math.cosh(rad)}\")\n",
        "        elif choice == '9':\n",
        "            print(f\"Result: tanh({angle}°) = {math.tanh(rad)}\")\n",
        "    elif choice in ['4', '5', '6']:\n",
        "        value = get_number(\"Enter value (-1 to 1 for asin/acos): \")\n",
        "        if choice == '4':\n",
        "            if -1 <= value <= 1:\n",
        "                print(f\"Result: sin⁻¹({value}) = {math.degrees(math.asin(value))}°\")\n",
        "            else:\n",
        "                print(\"Error: Value must be between -1 and 1 for inverse sine.\")\n",
        "        elif choice == '5':\n",
        "            if -1 <= value <= 1:\n",
        "                print(f\"Result: cos⁻¹({value}) = {math.degrees(math.acos(value))}°\")\n",
        "            else:\n",
        "                print(\"Error: Value must be between -1 and 1 for inverse cosine.\")\n",
        "        elif choice == '6':\n",
        "            print(f\"Result: tan⁻¹({value}) = {math.degrees(math.atan(value))}°\")\n",
        "    else:\n",
        "        print(\"Invalid choice.\")\n",
        "\n",
        "# Logarithmic functions\n",
        "def logarithmic_functions():\n",
        "    print(\"\\nLogarithmic Functions\")\n",
        "    print(\"1. Natural Log (ln)\")\n",
        "    print(\"2. Logarithm base 10 (log10)\")\n",
        "    print(\"3. Custom Base Logarithm\")\n",
        "\n",
        "    choice = input(\"Select a function (1-3): \")\n",
        "    num = get_number(\"Enter number: \")\n",
        "\n",
        "    if num <= 0:\n",
        "        print(\"Error: Logarithm is only defined for positive numbers.\")\n",
        "        return\n",
        "\n",
        "    if choice == '1':\n",
        "        print(f\"Result: ln({num}) = {math.log(num)}\")\n",
        "    elif choice == '2':\n",
        "        print(f\"Result: log10({num}) = {math.log10(num)}\")\n",
        "    elif choice == '3':\n",
        "        base = get_number(\"Enter logarithm base: \")\n",
        "        if base <= 0 or base == 1:\n",
        "            print(\"Error: Logarithm base must be positive and not equal to 1.\")\n",
        "        else:\n",
        "            print(f\"Result: log{base}({num}) = {math.log(num, base)}\")\n",
        "    else:\n",
        "        print(\"Invalid choice.\")\n",
        "\n",
        "# Matrix operations\n",
        "def matrix_operations():\n",
        "    print(\"\\nMatrix Operations\")\n",
        "    print(\"1. Matrix Addition\")\n",
        "    print(\"2. Matrix Subtraction\")\n",
        "    print(\"3. Matrix Multiplication\")\n",
        "    print(\"4. Matrix Determinant\")\n",
        "    print(\"5. Matrix Inverse\")\n",
        "    print(\"6. Matrix Trace\")\n",
        "    print(\"7. Eigenvalues and Eigenvectors\")\n",
        "    print(\"8. Solve Systems of Linear Equations\")\n",
        "    print(\"9. Matrix Transpose\")\n",
        "    print(\"10. Matrix Rank\")\n",
        "\n",
        "    choice = input(\"Select an operation (1-10): \")\n",
        "\n",
        "    if choice in ['1', '2', '3']:\n",
        "        matrix1 = get_matrix(\"Enter first matrix: \")\n",
        "        matrix2 = get_matrix(\"Enter second matrix: \")\n",
        "\n",
        "        if choice == '1':\n",
        "            if matrix1.shape != matrix2.shape:\n",
        "                print(\"Error: Matrices must have the same dimensions for addition.\")\n",
        "            else:\n",
        "                result = np.add(matrix1, matrix2)\n",
        "                print(\"Result:\\n\", result)\n",
        "        elif choice == '2':\n",
        "            if matrix1.shape != matrix2.shape:\n",
        "                print(\"Error: Matrices must have the same dimensions for subtraction.\")\n",
        "            else:\n",
        "                result = np.subtract(matrix1, matrix2)\n",
        "                print(\"Result:\\n\", result)\n",
        "        elif choice == '3':\n",
        "            try:\n",
        "                result = np.matmul(matrix1, matrix2)\n",
        "                print(\"Result:\\n\", result)\n",
        "            except ValueError:\n",
        "                print(\"Error: Matrix dimensions incompatible for multiplication.\")\n",
        "\n",
        "    elif choice in ['4', '5', '6', '7', '9', '10']:\n",
        "        matrix = get_matrix(\"Enter matrix: \")\n",
        "\n",
        "        if choice == '4':\n",
        "            if matrix.shape[0] != matrix.shape[1]:\n",
        "                print(\"Error: Matrix must be square to calculate determinant.\")\n",
        "            else:\n",
        "                try:\n",
        "                    determinant = np.linalg.det(matrix)\n",
        "                    print(f\"Result: Determinant = {determinant}\")\n",
        "                except np.linalg.LinAlgError:\n",
        "                    print(\"Error: Unable to compute determinant.\")\n",
        "\n",
        "        elif choice == '5':\n",
        "            if matrix.shape[0] != matrix.shape[1]:\n",
        "                print(\"Error: Matrix must be square to calculate inverse.\")\n",
        "            else:\n",
        "                try:\n",
        "                    inverse_matrix = np.linalg.inv(matrix)\n",
        "                    print(\"Result: Inverse Matrix:\\n\", inverse_matrix)\n",
        "                except np.linalg.LinAlgError:\n",
        "                    print(\"Error: Matrix is singular (not invertible).\")\n",
        "\n",
        "        elif choice == '6':\n",
        "            if matrix.shape[0] != matrix.shape[1]:\n",
        "                print(\"Error: Matrix must be square to calculate trace.\")\n",
        "            else:\n",
        "                trace = np.trace(matrix)\n",
        "                print(f\"Result: Trace = {trace}\")\n",
        "\n",
        "        elif choice == '7':\n",
        "            if matrix.shape[0] != matrix.shape[1]:\n",
        "                print(\"Error: Matrix must be square to calculate eigenvalues.\")\n",
        "            else:\n",
        "                try:\n",
        "                    eigenvalues, eigenvectors = np.linalg.eig(matrix)\n",
        "                    print(f\"Eigenvalues:\\n{eigenvalues}\")\n",
        "                    print(f\"Eigenvectors:\\n{eigenvectors}\")\n",
        "                except np.linalg.LinAlgError:\n",
        "                    print(\"Error: Unable to compute eigenvalues/eigenvectors.\")\n",
        "\n",
        "        elif choice == '9':\n",
        "            print(\"Result (Transposed Matrix):\\n\", matrix.T)\n",
        "\n",
        "        elif choice == '10':\n",
        "            print(f\"Result: Matrix Rank = {np.linalg.matrix_rank(matrix)}\")\n",
        "\n",
        "    elif choice == '8':\n",
        "        print(\"Solving systems of linear equations in the form Ax = b\")\n",
        "        A = get_matrix(\"Enter coefficient matrix A: \")\n",
        "        b = get_matrix(\"Enter constant vector b (as a single column): \")\n",
        "\n",
        "        if A.shape[0] != b.shape[0]:\n",
        "            print(\"Error: Number of rows in A must match rows in b.\")\n",
        "        else:\n",
        "            try:\n",
        "                solution = np.linalg.solve(A, b)\n",
        "                print(f\"Solution:\\n{solution}\")\n",
        "            except np.linalg.LinAlgError:\n",
        "                print(\"Error: Unable to solve the system (matrix may be singular).\")\n",
        "            except ValueError:\n",
        "                print(\"Error: b must be a single column vector.\")\n",
        "\n",
        "    else:\n",
        "        print(\"Invalid choice.\")\n",
        "\n",
        "# Advanced operations\n",
        "def advanced_operations():\n",
        "    print(\"\\nAdvanced Operations\")\n",
        "    print(\"1. Exponentiation (Power)\")\n",
        "    print(\"2. Square Root\")\n",
        "    print(\"3. Factorial\")\n",
        "    print(\"4. Absolute Value\")\n",
        "    print(\"5. Ceiling\")\n",
        "    print(\"6. Floor\")\n",
        "    print(\"7. Degrees to Radians\")\n",
        "    print(\"8. Radians to Degrees\")\n",
        "    print(\"9. GCD (Greatest Common Divisor)\")\n",
        "    print(\"10. LCM (Least Common Multiple)\")\n",
        "\n",
        "    choice = input(\"Select an operation (1-10): \")\n",
        "\n",
        "    if choice == '1':\n",
        "        base = get_number(\"Enter the base number: \")\n",
        "        exponent = get_number(\"Enter the exponent: \")\n",
        "        print(f\"Result: {base} ^ {exponent} = {base ** exponent}\")\n",
        "\n",
        "    elif choice == '2':\n",
        "        num = get_number(\"Enter number: \")\n",
        "        if num < 0:\n",
        "            print(\"Error: Cannot calculate square root of a negative number.\")\n",
        "        else:\n",
        "            print(f\"Result: √{num} = {math.sqrt(num)}\")\n",
        "\n",
        "    elif choice == '3':\n",
        "        num = get_number(\"Enter number: \")\n",
        "        if num < 0:\n",
        "            print(\"Error: Factorial is not defined for negative numbers.\")\n",
        "        elif not num.is_integer():\n",
        "            print(\"Error: Factorial is only defined for integers.\")\n",
        "        else:\n",
        "            print(f\"Result: {int(num)}! = {math.factorial(int(num))}\")\n",
        "\n",
        "    elif choice == '4':\n",
        "        num = get_number(\"Enter number: \")\n",
        "        print(f\"Result: |{num}| = {abs(num)}\")\n",
        "\n",
        "    elif choice == '5':\n",
        "        num = get_number(\"Enter number: \")\n",
        "        print(f\"Result: ceil({num}) = {math.ceil(num)}\")\n",
        "\n",
        "    elif choice == '6':\n",
        "        num = get_number(\"Enter number: \")\n",
        "        print(f\"Result: floor({num}) = {math.floor(num)}\")\n",
        "\n",
        "    elif choice == '7':\n",
        "        deg = get_number(\"Enter degrees: \")\n",
        "        print(f\"Result: {deg}° = {math.radians(deg)} radians\")\n",
        "\n",
        "    elif choice == '8':\n",
        "        rad = get_number(\"Enter radians: \")\n",
        "        print(f\"Result: {rad} radians = {math.degrees(rad)}°\")\n",
        "\n",
        "    elif choice == '9':\n",
        "        num1 = int(get_number(\"Enter first integer: \"))\n",
        "        num2 = int(get_number(\"Enter second integer: \"))\n",
        "        print(f\"Result: GCD({num1}, {num2}) = {math.gcd(num1, num2)}\")\n",
        "\n",
        "    elif choice == '10':\n",
        "        num1 = int(get_number(\"Enter first integer: \"))\n",
        "        num2 = int(get_number(\"Enter second integer: \"))\n",
        "        gcd = math.gcd(num1, num2)\n",
        "        lcm = abs(num1 * num2) // gcd if gcd != 0 else 0\n",
        "        print(f\"Result: LCM({num1}, {num2}) = {lcm}\")\n",
        "\n",
        "    else:\n",
        "        print(\"Invalid choice.\")\n",
        "\n",
        "# Main function\n",
        "def main():\n",
        "    print(\"Welcome to the Comprehensive Scientific Calculator!\")\n",
        "    print(\"You can enter any real numbers (positive, negative, decimals) for calculations.\")\n",
        "\n",
        "    while True:\n",
        "        display_menu()\n",
        "        choice = input(\"Enter your choice (1-6): \")\n",
        "\n",
        "        if choice == '1':\n",
        "            basic_arithmetic()\n",
        "        elif choice == '2':\n",
        "            trigonometric_functions()\n",
        "        elif choice == '3':\n",
        "            logarithmic_functions()\n",
        "        elif choice == '4':\n",
        "            matrix_operations()\n",
        "        elif choice == '5':\n",
        "            advanced_operations()\n",
        "        elif choice == '6':\n",
        "            print(\"Exiting the program. Goodbye!\")\n",
        "            break\n",
        "        else:\n",
        "            print(\"Invalid choice. Please try again.\")\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "display_name": ".venv",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.13.3"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
