# -*- coding: utf-8 -*-
"""Armstrong-Number-in-Interval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tm8mvpHsKM26LbMZIAMut-2CtRgSmLtP

like we have 407=(4x4x4)+(0x0x0)+(7x7x7)=407 so this is armstrong number
like we when have 27=2x2+7x7=53 not an armstrong
"""

lower=int(input('Enter the lower limit here: '))
uper=int(input('Enter the uper limit here: '))
for num in range(lower,uper+1):
  order=len(str(num))
  sum=0
  temp=num
  while temp>0:
    digit=temp%10
    sum+=digit**order
    temp//=10
  if num == sum:
    print(num)